/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 343d2b68b80a526e2dd204fd8db65652)
interface __BaseEnv_Env {
  DB: D1Database;
  EMAIL: SendEmail;
  ADMIN_RATE_LIMITER: RateLimit;
  AUTH_RATE_LIMITER: RateLimit;
  API_RATE_LIMITER: RateLimit;
  OFFER_RATE_LIMITER: RateLimit;
  STRIPE_PRO_PRICE_ID: 'price_1UAvtYEFWzXv59QZgttvSlRI';
  STRIPE_TEAM_PRICE_ID: 'price_1UAvtZEFWzXv59QZdkZdmcud';
  STRIPE_INTRO_COUPON_ID: 'omg_intro_20_3mo_v1';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'STRIPE_PRO_PRICE_ID' | 'STRIPE_TEAM_PRICE_ID' | 'STRIPE_INTRO_COUPON_ID'>
  > {}
}
declare module '*.txt' {
  const value: string;
  export default value;
}
declare module '*.html' {
  const value: string;
  export default value;
}
declare module '*.sql' {
  const value: string;
  export default value;
}
declare module '*.bin' {
  const value: ArrayBuffer;
  export default value;
}
declare module '*.wasm' {
  const value: WebAssembly.Module;
  export default value;
}
declare module '*.wasm?module' {
  const value: WebAssembly.Module;
  export default value;
}
